version: '3'
services:
  app:
    image: mvaload/devops-for-programmers-project-74
    build:
      context: ./
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

    command: npm test
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
