version: '3'
services:
  app:
    image: mvaload/devops-for-programmers-project-74
    build:
      context: ./
      dockerfile: Dockerfile.production
    command: npm test
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
