version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make start
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  caddy:
    image: caddy:2.6.0-alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443