name: ci

on:
  push:
    branches:
      - main

env:
  RODUCTION_IMAGE_TAG: mvaload/devops-for-programmers-project-74:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.production
          tags: ${{ env.PRODUCTION_IMAGE_TAG }}